### ISSUE TITLE
not working with Grails 3.0.17

### ISSUE THREAD

**Issue by rvanderwerf** [grails/grails-views#44]
Docs say 3.0 and higher. Client and myself can't get a base 3.0.17 app with installed per the docs. This is the error we get:
grails> run-app
| Running application...
Exception in thread "main" java.lang.IllegalArgumentException: Cannot instantiate interface org.springframework.context.ApplicationListener : org.springframework.boot.logging.ClasspathLoggingApplicationListener
	at org.springframework.boot.SpringApplication.createSpringFactoriesInstances(SpringApplication.java:414)
	at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:394)
	at org.springframework.boot.SpringApplication.getSpringFactoriesInstances(SpringApplication.java:385)
	at org.springframework.boot.SpringApplication.initialize(SpringApplication.java:263)
	at org.springframework.boot.SpringApplication.<init>(SpringApplication.java:237)
	at grails.boot.GrailsApp.<init>(GrailsApp.groovy)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:374)
	at grails.boot.GrailsApp.run(GrailsApp.groovy:363)
	at grails.boot.GrailsApp$run.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
	at viewstest.Application.main(Application.groovy:8)
Caused by: java.lang.NoClassDefFoundError: org/springframework/context/event/GenericApplicationListener
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at org.springframework.util.ClassUtils.forName(ClassUtils.java:249)
	at org.springframework.boot.SpringApplication.createSpringFactoriesInstances(SpringApplication.java:407)
	... 12 more
Caused by: java.lang.ClassNotFoundException: org.springframework.context.event.GenericApplicationListener
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 26 more

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':bootRun'.
> Process 'command '/usr/lib/jvm/java-7-oracle/bin/java'' finished with non-zero exit value 1

Attaching sample app.

**Comment by rvanderwerf** [comment]
[viewsTest.zip](https://github.com/grails/grails-views/files/268891/viewsTest.zip)
attached sample app. It appears it worked up until 1.0.0-RC1.

**Comment by graemerocher** [comment]
The issue is the Gradle plugin pulling in a newer version of Grails and Spring Boot. You have to alter your build as follows:

```groovy
        classpath "org.grails.plugins:views-gradle:1.0.10-SNAPSHOT", {
            exclude group:"org.grails", module:'grails-gradle-plugin'
        }
```
